qtbase: fix build with gcc-9
* some components which use Werror started to fail with gcc-9, because of new warning:
  https://gcc.gnu.org/gcc-9/changes.html
  New warnings:
    -Wdeprecated-copy, implied by -Wextra, warns about the C++11
       deprecation of implicitly declared copy constructor and
       assignment operator if one of them is user-provided.
       -Wdeprecated-copy-dtor also warns if the destructor is
       user-provided, as specified in C++11.
* e.g. maliit-framework-qt5 was now failing with:
  maliit-framework-qt5/0.99.0+gitAUTOINC+62bd54bcde-r0/recipe-sysroot/usr/include/QtCore/qvariant.h:273:25:
  error: implicitly-declared 'constexpr QVariant::Private& QVariant::Private::operator=(const QVariant::Private&)' is deprecated [-Werror=deprecated-copy]
  273 |     { other.d = Private(); }
      |                         ^

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>