qtbase: add no-opengl to PACKAGECONFIG_GL when opengl isn't in DISTRO_FEATURES
* otherwise building qtbase with default config will fail with:
  ERROR: The OpenGL functionality tests failed!
  You might need to modify the include and library search paths by editing
  QMAKE_INCDIR_OPENGL[_ES2], QMAKE_LIBDIR_OPENGL[_ES2] and QMAKE_LIBS_OPENGL[_ES2]
  in the mkspec for your platform.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Gaël PORTAY <gael.portay@gmail.com>